plugins:

    puppet_plugin:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            url: https://github.com/Fewbytes/cloudify-plugin-puppet/archive/master.zip

imports:
    - cloudify.openstack
    # LATER # - cloudify.puppet
    - puppet-type-server.yaml

blueprint:
    name: system-test-puppet-master
    nodes:
        -   name: puppet_server
            type: cloudify.openstack.server
            properties:
                install_agent: true
                worker_config:
                    port: 22
                    user: ubuntu
                    key: REPLACED-BY-TEST
                management_network_name: REPLACED-BY-TEST
                server:
                    name: REPLACED-BY-TEST
                    image_name: REPLACED-BY-TEST
                    flavor_name: REPLACED-BY-TEST
                    key_name: REPLACED-BY-TEST
                    security_groups: [puppet_sg]  # MODIFIED-BY-TEST (adds agents security group to the list)
                    # MODIFIED-BY-TEST -- {hostname} substitution
                    userdata: |
                        #!/bin/bash -ex
                        grep -q "{hostname}" /etc/hosts || echo "127.0.0.1 {hostname}" >> /etc/hosts
            relationships:
                -   type: cloudify.openstack.server_connected_to_floating_ip
                    target: ip
                -   type: cloudify.relationships.connected_to
                    target: puppet_sg
        -   name: ip
            type: cloudify.openstack.floatingip
            properties:
                floatingip:
                    floating_network_name: REPLACED-BY-TEST
        -   name: puppet_sg
            type: cloudify.openstack.security_group
            properties:
                security_group:
                    name: puppet_sg
                rules:
                    -   remote_ip_prefix: 0.0.0.0/0
                        port: 22
                    -   remote_ip_prefix: 0.0.0.0/0
                        port: 8140
        -   name: puppet_service
            type: middleware_server_puppet
            properties:
                puppet_config:
                    server: puppet
                    environment: cloudify0system0test
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: puppet_server

