plugins:

    puppet_plugin:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            url: https://github.com/Fewbytes/cloudify-plugin-puppet/archive/master.zip
            # folder: cloudify-plugin-puppet

imports:
    - cloudify.openstack
    - puppet-type.yaml

blueprint:
    name: puppet-agent-system-test
    nodes:
        -
            name: server-for-puppet-agent
            type: cloudify.openstack.server
            properties:
                install_agent: true
                worker_config:
                    port: 22
                    user: ubuntu
                    key: REPLACED-BY-TEST
                management_network_name: REPLACED-BY-TEST
                server:
                    name: REPLACED-BY-TEST
                    image_name: REPLACED-BY-TEST
                    flavor_name: REPLACED-BY-TEST
                    key_name: REPLACED-BY-TEST
                    security_groups: [puppet_sg]  # MODIFIED-BY-TEST (adds agents security group to the list)
                    # MODIFIED-BY-TEST -- {hostname} substitution
                    userdata: |
                        #!/bin/bash -ex
                        grep -q puppet /etc/hosts || echo "{puppet_server_ip} puppet" >> /etc/hosts
            relationships:
                -   type: cloudify.openstack.server_connected_to_floating_ip
                    target: ip
        -
            name: puppet_node_one
            type: db_server_puppet
            properties:
                puppet_config:
                    add_operation_tag: True,
                    operations_tags:
                        create: [op_tag_create, tag2]
                    environment: e1
                    tags: [a, b]
                    server: puppet
                    node_name_prefix: pfx-
                    node_name_suffix: .puppet.example.com
            relationships:
                -
                    type: cloudify.relationships.contained_in
                    # target: existing_server
                    target: server-for-puppet-agent

        -   name: ip
            type: cloudify.openstack.floatingip
            properties:
                floatingip:
                    floating_network_name: REPLACED-BY-TEST
