version: 2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

jobs:
  flake8:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout
      - run: pip install --user flake8
      - run: python -m flake8

workflows:
  version: 2

  run_test:
    jobs:
      - flake8
