#######
# Cloudify Hello World blueprint.
#
# The blueprint describes a Libcloud vm created using Cloudify's Libcloud plugin
# and simple web server started using Cloudify's bash plugin.
# In addition, a Libcloud floating ip and security group are created and associated with the created vm.
#

imports:
    - https://raw.githubusercontent.com/AlexRaskosov/cloudify-libcloud-plugin/develop/plugin.yaml
    - http://www.getcloudify.org/spec/bash-plugin/1.0/plugin.yaml

types:
    # A web server configured with bash scripts
    cloudify.types.bash.web_server_with_index_and_image:
        derived_from: cloudify.types.bash.web_server
        properties:
            - image_path
            - index_path

# The blueprint contains two nodes, a vm and a web server hosted in it.
blueprint:
    name: hello_world
    nodes:
        -   name: virtual_ip
            type: cloudify.libcloud.floatingip

        -   name: security_group
            type: cloudify.libcloud.security_group
            properties:
                security_group:
                    name: webserver_security_group
                rules:
                    -   remote_ip_prefix: 0.0.0.0/0
                        port: 8080

        -   name: vm
            type: cloudify.libcloud.server
            instances:
                deploy: 1
            properties:
                cloudify_agent:
                    user: ubuntu
                server:
                    name: bash-web-server
                    image_name: ami-fa7dba92
                    size_name: m1.medium
                    key_name: cloudify-agents-kp
                    security_groups: ['webserver_security_group']
            relationships:
                -   type: cloudify.libcloud.server_connected_to_floating_ip
                    target: virtual_ip
                -   type: cloudify.relationships.connected_to
                    target: security_group

        -   name: http_web_server
            type: cloudify.types.bash.web_server_with_index_and_image
            properties:
                port: 8080
                image_path: images/cloudify-logo.png
                index_path: index.html
                scripts:
                    configure: scripts/configure.sh
                    start: scripts/start.sh
                    stop: scripts/stop.sh
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: vm

