premium:
  description: Whether to run tests on premium or community. If false, tests will be run on community.
  default: true
target_platform:
  description: Which platform to deploy test resources on.
  default: openstack
  valid_values: [openstack, aws]
testing_version:
  description: Which manager version we're testing. Note that this is expected to be in the form <version number>-<identifier>. Bad things may happen without the hyphen.
  default: 6.4.2-ga
