premium:
  description: Whether to run tests on premium or community. If false, tests will be run on community.
target_platform:
  description: Which platform to deploy test resources on.
  default: openstack
  valid_values: [openstack, aws]
testing_version:
  description: Which manager version we're testing.
  default: 6.0.0-.dev1
