apiVersion: v1
kind: Pod
spec:
  containers:
    - name: py36
      image: python:3.6
      resources:
        requests:
          cpu: 1
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        privileged: true
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot
