apiVersion: v1
kind: Pod
spec:
  containers:
    - name: python
      image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-python3.11
      resources:
        requests:
          cpu: 1
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        privileged: true
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot
