pipeline {
  agent {
    kubernetes {
      label "system-tests-mb-${env.BUILD_NUMBER}"
      defaultContainer 'jnlp'
      yamlFile 'jenkins/build-pod.yaml'
    }
  }

  options {
    checkoutToSubdirectory('cloudify-system-tests')
    buildDiscarder(logRotator(numToKeepStr:'10'))
    timeout(time: 80, unit: 'MINUTES')
    timestamps()
  }

  environment{
    PROJECT = "cloudify-system-tests"
  }

  stages {
    stage('No name') {
      steps {
       echo 'hello'
      }
    }
  }
}
