pipeline {
  agent {
    kubernetes {
      label "system-tests-mb-${env.BUILD_NUMBER}"
      defaultContainer 'jnlp'
      yamlFile 'jenkins/build-pod.yaml'
    }
  }

  options {
    checkoutToSubdirectory('cloudify-system-tests')
    buildDiscarder(logRotator(numToKeepStr:'10'))
    timeout(time: 60, unit: 'MINUTES')
    timestamps()
  }

  environment{
    PROJECT = "cloudify-system-tests"
  }

  stages {
    stage('flake8') {
      steps {
        sh script: "mkdir -p ${env.WORKSPACE}/flake8 && cp -rf ${env.WORKSPACE}/${env.PROJECT}/. ${env.WORKSPACE}/flake8", label: "copying repo to seperate workspace"

        container('py36'){
          dir("${env.WORKSPACE}/flake8") {
            sh script:'''
              pip install --user flake8
              python -m flake8
              ''', label: 'Install and run flake8'
          }
        }
      }
    }
    stage('collect tests') {
      steps {
        container('py36'){
            sh script:'''
            pip install -r ${WORKSPACE}/${PROJECT}/requirements.txt --user
            python --collect-only ${WORKSPACE}/${PROJECT}/cosmo_tester
            ''', label: 'Collect all tests'
        }
      }
    }
  }
}
