#!/bin/bash

CLI_PACKAGE_URL=$1
PRIVATE_IP=$2
TENANT=$3

echo "Installing Cloudify's CLI..."
echo "Using CLI package: ${CLI_PACKAGE_URL}"

which rpm

if [ "$?" -eq "0" ]; then
    sudo rpm -i ${CLI_PACKAGE_URL}
else
    wget ${CLI_PACKAGE_URL} -O cloudify-cli.deb
    sudo dpkg -i cloudify-cli.deb
fi

# This ensures that if one of the commands fails, the whole execution fails
set -e

cfy profiles use ${PRIVATE_IP} -u admin -p admin -t ${TENANT}

cfy blueprints upload -b test_bp /tmp/test_blueprint/blueprint.yaml
cfy deployments create -b test_bp test_dep -i /tmp/test_blueprint/inputs.yaml
cfy executions start install -d test_dep
